"use client";

import React from "react";
import { Sparkles, BrainCircuit } from "lucide-react";

interface MarketSummaryProps {
  summary: string;
  symbol: string;
}

export default function MarketSummary({ summary, symbol }: MarketSummaryProps) {
  const cleanSymbol = symbol.replace("USDT", "");

  return (
    <div className="bg-card border border-border rounded-2xl p-6 flex flex-col justify-between relative overflow-hidden shadow-sm hover:shadow-md transition-all h-full bg-gradient-to-r from-primary/[0.03] to-transparent">
      {/* Decorative light effect */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>

      <div className="flex items-center gap-2 text-muted-foreground text-[10px] font-bold uppercase tracking-wider mb-4 shrink-0">
        <BrainCircuit size={14} className="text-primary animate-pulse" />
        <span>Market Intelligence Summary ({cleanSymbol})</span>
      </div>

      <div className="flex-1">
        <div className="space-y-2">
          <p className="text-foreground/90 text-sm leading-relaxed font-medium">
            {summary}
          </p>
          <p className="text-[10px] text-muted-foreground/60 italic font-mono">
            * Generated by real-time quantitative rules engine parsing moving averages, momentum channels, and volatility metrics.
          </p>
        </div>
      </div>
    </div>
  );
}
